#+title: Musings
#+language: ru

План работы. Пока жду набросков сервера и макета сайта, куда можно вставить код для рендера и обработки запросов. Также
на мне инфраструктура и интеграция трёх частей.

* Инфраструктура
В докер это всё помещено. Требуется продолжение поддержки контейнера докера. Как хост для общего репозитория
используется виртуальная машина со статическим IP, без выч. мощности. Есть сервер без публичного IP, буду думать о
прокси.

* Рендер
Буду работать над формализацией API и реализацией отображения следующих задач:

Общей проблемой скорее всего будет потеря точности при конвертации в json и обратно. [[https://developers.google.com/protocol-buffers][Protocol buffers]] позволяет этого
избежать, но немного усложняет реализацию приёма/передачи сообщений.

** Решение уравнений

Поиск корня уравнения. Пользователь может задавать функцию, промежуток с корнем.

Нюанс: явно нужен график функции. Можно послать на сервер и ждать точек, но может получиться долго. Если считать
локально, может получиться ещё дольше.

Получаем последовательность пар ~<аргумент, значение>~. Это подходит для всех методов.

** СЛАУ и другие матричные задачи
Получаем матрицу заданного размера. В общем то всё.

Надо работать над анимациями, которые скорее всего будут специфичны для каждого метода

** Интерполяция

Относительно лёгкая задача.

В =PixiJS= квадратичные кривые и кривые Безье это примитивы, что сильно упрощает работу с интерполяцией сплайнами.
Получаем последовательность ~<границы, кривая>~

Для интерполяции полиномом данные совпадают с данными для графика функции


** Численное интегрирование

Требуется график функции.

Для форм Ньютона-Котеса также последовательность вида ~<границы, кривая>~. Более сложные формы плохо поддаются
визуализации, так как нет представления в виде кривой.
