# Generated by Django 4.1.4 on 2022-12-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInteractions', '0002_adminnames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNames',
        ),
    ]
