# Generated by Django 4.1.4 on 2022-12-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInteractions', '0003_delete_adminnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
