# Generated by Django 4.1.4 on 2022-12-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInteractions', '0004_userlogin_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
