# Generated by Django 4.1.4 on 2022-12-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleInteractions', '0005_alter_userlogin_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
